/**
 * 角色管理结构
 */
import {
  /** @module 应用中心 */
  APP_CENTER,
  APP_CENTER_LIST,
  /** @module 设备管理 */
  EQUIPMENT,
  EQUIPMENT_LIST,
  EQUIPMENT_DETAIL,
  EQUIPMENT_IMPORT,
  EQUIPMENT_ADD,
  EQUIPMENT_DELETE,
  EQUIPMENT_MODIFY,
  /** @module 系统管理 */
  SYSTEM,
  // 系统配置
  SYSTEM_CONFIG_LIST,
  SYSTEM_CONFIG_ADD,
  SYSTEM_CONFIG_DELETE,
  SYSTEM_CONFIG_MODIFY,
  // 系统配置详情
  SYSTEM_CONFIG_DETAIL,
  SYSTEM_CONFIG_DETAIL_ADD,
  SYSTEM_CONFIG_DETAIL_MODIFY,
  /** @module 账户管理 */
  ACCOUNT,
  // 用户管理
  ACCOUNT_USER,
  ACCOUNT_USER_ADD,
  ACCOUNT_USER_MODIFY,
  ACCOUNT_USER_ENABLE,
  ACCOUNT_USER_DISABLE,
  ACCOUNT_USER_DELETE,
  //  角色管理
  ACCOUNT_ROLE,
  ACCOUNT_ROLE_ADD,
  ACCOUNT_ROLE_MODIFY,
  ACCOUNT_ROLE_DELETE,
  // 组织管理
  ACCOUNT_ORGANIZATION,
  ACCOUNT_ORGANIZATION_ADD,
  ACCOUNT_ORGANIZATION_MODIFY,
  ACCOUNT_ORGANIZATION_DELETE,
  ACCOUNT_ORGANIZATION_API_CONFIG

} from './permissions'

/** @name 页面添加操作 */
// 应用中心
APP_CENTER_LIST.children = []
// 设备管理
EQUIPMENT_LIST.children = [
  EQUIPMENT_ADD,
  EQUIPMENT_MODIFY,
  EQUIPMENT_DELETE,
  EQUIPMENT_IMPORT,
  EQUIPMENT_DETAIL
]

// 系统管理
SYSTEM_CONFIG_LIST.children = [
  SYSTEM_CONFIG_ADD,
  SYSTEM_CONFIG_MODIFY,
  SYSTEM_CONFIG_DELETE,
  SYSTEM_CONFIG_DETAIL
]
SYSTEM_CONFIG_DETAIL.children = [
  SYSTEM_CONFIG_DETAIL_ADD,
  SYSTEM_CONFIG_DETAIL_MODIFY
]

// 用户管理
ACCOUNT_USER.children = [
  ACCOUNT_USER_ADD,
  ACCOUNT_USER_MODIFY,
  ACCOUNT_USER_DELETE,
  ACCOUNT_USER_ENABLE,
  ACCOUNT_USER_DISABLE
]
// 角色管理
ACCOUNT_ROLE.children = [
  ACCOUNT_ROLE_ADD,
  ACCOUNT_ROLE_MODIFY,
  ACCOUNT_ROLE_DELETE
]
// 组织管理
ACCOUNT_ORGANIZATION.children = [
  ACCOUNT_ORGANIZATION_ADD,
  ACCOUNT_ORGANIZATION_MODIFY,
  ACCOUNT_ORGANIZATION_DELETE,
  ACCOUNT_ORGANIZATION_API_CONFIG
]

/** @name 模块添加页面 */

APP_CENTER.children.push(
  APP_CENTER_LIST
)

// 设备管理模块
EQUIPMENT.children.push(
  EQUIPMENT_LIST
)

// 系统管理模块
SYSTEM.children.push(
  SYSTEM_CONFIG_LIST,
  SYSTEM_CONFIG_DETAIL
)

// 账户管理模块
ACCOUNT.children.push(
  ACCOUNT_USER,
  ACCOUNT_ROLE,
  ACCOUNT_ORGANIZATION
)

export default [
  APP_CENTER,
  EQUIPMENT,
  SYSTEM,
  ACCOUNT
]
